server:
  port: 8002
kafka:
  topics:
    processed: processed-video
    streaming: streaming-video
  producer:
    bootstrap-servers: 10.152.183.90:9094
#    bootstrap-servers: blue-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    key-serializer: serializer
    value-serializer: serializer
    acks: all
    compression-type: gzip

#https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html